version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=victor1234
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "3308:3306" # might need to change the port
    volumes:
      - ./data/mysgl:/var/lib/mysgl




